version: "3"

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
    - "3040:3040"